---
name: GDS2
version: 2.09
author: []
abstract: GDS2 stream module
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  perl: 5.6.0
provides:
  GDS2:
    file: lib/GDS2.pm
    version: 2.09
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
