---
name: GDS2
version: 2.05
author: ~
abstract: GDS2 stream module
license: artistic
requires:
  perl: 5.6.0
provides:
  GDS2:
    file: lib/GDS2.pm
    version: 2.05
generated_by: Module::Build version 0.261
