---
name: GDS2
version: 3.00
author: []
abstract: GDS2 stream module
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  perl: v5.8.0
configure_requires:
  Module::Build: 0.35
provides:
  GDS2:
    file: lib/GDS2.pm
    version: 3.00
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
